In [3]:
import numpy as np

Create a NumPy array of shape (3, 3) and add a constant scalar value to each element.

In [4]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(arr1+1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Create a NumPy array of shape (3, 1) and add it to a NumPy array of shape (1, 3).

In [6]:
arr1 = np.array([[1],
                 [2],
                 [3]])
arr2 = np.array([[4, 5, 6]])

print(arr1 + arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
