In [1]:
import numpy as np

Create two arrays of shape (2, 3) and stack them vertically.

In [2]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[7,8,9],
                 [4,7,2]])
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 7, 2]])

Create two arrays of shape (3, 2) and stack them horizontally.

In [5]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[7,8,9],
                 [4,7,2]])
np.hstack((arr1,arr2))

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 4, 7, 2]])

Split a 2D array of shape (4, 4) into four equal parts.

In [9]:
arr = np.array([[1,2,3,4],
                [4,5,6,7],
                [7,8,9,10],
                [10,11,12,13]])

# res = np.array_split(arr, 4) 
# print(res)

# np.hsplit(arr, 4) # horizontal partition (colm wize)
np.vsplit(arr, 4) # vertical partition (row wise)


[array([[1, 2, 3, 4]]),
 array([[4, 5, 6, 7]]),
 array([[ 7,  8,  9, 10]]),
 array([[10, 11, 12, 13]])]