In [1]:
import numpy as np

In [2]:
# Create a NumPy array of zeros of shape (3, 4).
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# Create a NumPy array of ones of shape (2, 3, 4).
arr = np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# Create a NumPy array with values ranging from 10 to 30.
arr = np.arange(10, 30, 1)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [5]:
# Reshape the array created in the previous step to shape (5, 4).
new_arr = arr.reshape(5, 4)
print(new_arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]
