In [1]:
import numpy as np

Compute the dot product of two matrices.

In [2]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

arr2 = np.array([[7,8,9],
                 [4,5,6],
                [1,2,3]])

print(arr1.dot(arr2))

[[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]


Compute the determinant of a square matrix.


In [3]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
det = np.linalg.det(arr1) 
print(arr1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Solve a system of linear equations represented by matrices.

In [4]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
x = np.linalg.solve(arr1, arr2)
print(x)


[[ 1.  0. -1.]
 [ 0.  1.  2.]
 [-0. -0. -0.]]
