In [1]:
import numpy as np

Reverse the order of elements in a 1D array.

In [2]:
arr = np.array([1,2,3])

print(arr[::-1])

[3 2 1]


Transpose a 2D array.

In [4]:
arr = np.array([[1,2,3,],
                 [4,5,6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


Flatten a 2D array into a 1D array.

In [10]:
arr = np.array([[1,2,3,],
                 [4,5,6]])

print(arr.flatten())

[1 2 3 4 5 6]
