In [2]:
import numpy as np

Create two NumPy arrays of shape (3, 3) and perform element-wise addition.

In [3]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [4]:
print(arr1+arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Create a NumPy array of shape (2, 2) and another array of shape (2, 1). Perform matrix multiplication between them.

In [5]:
arr1 = np.array([[1,2],
                 [3,4]])
arr2 = np.array([[5],
                 [5]])

In [6]:
print(arr1.dot(arr2))

[[15]
 [35]]


Create a NumPy array of shape (3, 3) and find the mean, median, and standard deviation of its elements.

In [7]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))


5.0
5.0
2.581988897471611
