In [13]:
import numpy as np

Compute the sum, min, max, and mean of a given array.

In [14]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(np.sum(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.mean(arr1))

45
1
9
5.0


Compute the cumulative sum along the columns of a 2D array.

In [15]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(arr1.cumsum(axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


Compute the correlation coefficient between two arrays. 

In [16]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# Compute the correlation coefficient matrix
correlation_matrix = np.corrcoef(arr1, arr2)
print(correlation_matrix)


[[ 1. -1.]
 [-1.  1.]]
