In [1]:
import numpy as np

Generate a random NumPy array of shape (2, 2) with values sampled from a standard normal distribution.

In [2]:
arr = np.random.randn(2, 2) # returns samples from the standard normal distribution, which has a mean of 0 and a standard deviation of 1.
print(arr)

[[ 0.06987588 -0.86889705]
 [-1.95707996 -0.60472114]]


Generate a random NumPy array of shape (3, 3) with integer values ranging from 1 to 10.

In [3]:
arr1 = np.random.randint(1, 11, size=(3, 3))
print(arr1)

[[6 1 8]
 [1 8 1]
 [1 6 7]]
